### ISSUE TITLE
Click on a Slider goes to top of page

### ISSUE THREAD

**Issue by pete1278** [IonDen/ion.rangeSlider#138]
Having an issue where clicking on the handlebar jumps to the top of the page. I have six sliders on the page. Any suggestions?

**Comment by SasiMallow** [comment]
Hi IonDen,

I too face the same issue but it fixed when I used " position: relative".
May I know the exact reason for this issue.

Thanks,

**Comment by IonDen** [comment]
Hi, @SasiMallow, this is because slider contains some hidden elements, which have absolute position and are getting focus in some cases.

In browser, normal behavior for focus - is to scroll viewport to this element. So, if element has position absolute and there are no other containers with position relative, the closest one will be BODY.

That is why pages scrolls up.
