### ISSUE TITLE
slider stop animate after 2 steps

### ISSUE THREAD

**Issue by PALLY27** [IonDen/ion.rangeSlider#354]
I have this code in angularJS. I wanna percentage ratio info bellow slider. it looks like this:

<img width="552" alt="screenshot at feb 26 10-26-14" src="https://cloud.githubusercontent.com/assets/16815519/13348371/6a6e67ba-dc73-11e5-9379-6341577b21c7.png">
 
It's working, but animation of slider stop after two steps, and I must click again to slider to next slider moving. 

Any ideas why it's stops ? and how to repair it ? 

```javascript
$('.boostItRatio01').ionRangeSlider({
            hide_min_max: true,
            min: 0,
            max: 100,
            from: 50,
            step: 10,
            prefix: $scope.ratio + "/",

            onStart: function (data) {
                $scope.ratio = data.from;
            },
            onChange: function (data) {
                $scope.ratio = data.max - data.from;
                updateSlider01();
            }
        });
        var slider01 = $(".boostItRatio01").data("ionRangeSlider");

        function updateSlider01() {
            slider01.update({
                prefix: $scope.ratio + "/"
            });
        }
```

**Comment by IonDen** [comment]
Hi, this is because you call slider update inside onChange callback.
Now update will redraw full slider instance and reset all event handlers, that is why you will need to click it again (not doing this is in future plans).

For now, you should avoid doing so. Instead you should use **prettify** function to change the visual values (check demo for that).

**Comment by PALLY27** [comment]
Thank you :)
