### ISSUE TITLE
Ion range slider 2 input

### ISSUE THREAD

**Issue by Aadencoder** [IonDen/ion.rangeSlider#443]
http://jsfiddle.net/y9dmpj6y/1/

what I am doing wrong here. I want the value to been shown respectively. But instead only one place holder is active and receiving both slider value.

**Comment by IonDen** [comment]
Hello, this is happened because you are using the same update function for both sliders. You overwriting the first one with second one.

Just check this, if you have slider_1 and slider_2, so, all the functions and vars should be also named like that, to avoid problems: update_1 (), update_2 (), from_1, from_2 and so on.

**Comment by Aadencoder** [comment]
thnx for quick response will try this/....

**Comment by Aadencoder** [comment]
I implement directly on my working code and it started working as charm. thanks a lot you saved my day.

**Comment by IonDen** [comment]
@Aadencoder NP
