### ISSUE TITLE
Moving the slider on IE8 browser can cause the Kendo's dropdown unselectable

### ISSUE THREAD

**Issue by sawas** [IonDen/ion.rangeSlider#468]
Lately i've beed found that 

`$("*").prop("unselectable", false);`

it do make all element in my web unselectable even all of the Kendo's dropdown were unselectable too.

so i've to make change the code a bit by select the class that starting with `irs` 

`$('[class^="irs"]').prop("unselectable", false);`

sorry for my poor english.

**Comment by IonDen** [comment]
Hello, @sawas. This is not a bug. All elements should become unselectable on slider use because otherwise cursor will select everything around while moving handle. Not everybody are so accurate to move handle only above slider itself, you can drag cursor all around the page.

If you will look at the code, you will see, that this unselectable prop was added temporary:

on mouse down i'm adding it:
https://github.com/IonDen/ion.rangeSlider/blob/master/js/ion.rangeSlider.js#L795

on mouse up i'm removing it:
https://github.com/IonDen/ion.rangeSlider/blob/master/js/ion.rangeSlider.js#L746
