### ISSUE TITLE
Update value in real time

### ISSUE THREAD

**Issue by dmrathore** [IonDen/ion.rangeSlider#487]
Hello 
I am using ion range slider in my project for real time brightness control , How to update value in real time using database operation for the other clients.

thanks

**Comment by IonDen** [comment]
Hello, i did not understand what exactly you need. Could you provide more details?

Updating slider:
http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html#range_50

Getting slider value in realtime:
http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html#range_46

**Comment by RomanBurunkov** [comment]
Hello @IonDen ,

Could you please clarify whether update method redraw all slider instance or not?

Asking that because in my case I have a bunch of ionRangeSliders on one page which I update every 5 seconds by update method. 

I need to update only slider value, not all slider options like from/to etc... but it looks like if I call an update method whole slider redraws.

That's causing some performance issues on weak hardware.

**Comment by RomanBurunkov** [comment]
That's probably related to #328
