### ISSUE TITLE
To/from handles jump to position when showing parent from display:none;

### ISSUE THREAD

**Issue by marcobaldo** [IonDen/ion.rangeSlider#488]
I have a slider inside a div that is set to `display: none;` initially.

When I set the div to show (e.g. `display: block;` or anything else - on `.css:hover` in this case), I see the slider rendered correctly except for a few milliseconds of delay before the slider handles (to/from) as well as their corresponding labels show up in their correct spots.

Everything else is rendered correctly - the bar, the grids, the min/max labels, etc. In the attached screenshot, the top part is the initial portion, and the bottom part is the expected outcome, which only shows after a few milliseconds.

![image](https://user-images.githubusercontent.com/1984893/28265905-b803a2c4-6b24-11e7-8528-828d66c45bc9.png)

**Comment by IonDen** [comment]
Hello. This is the common problem for everything which is initialized inside `display: none` blocks.
Happens because it is impossible to measure sliders size inside hidden block. All measurements will just return 0.

Common workaround to fix this:
1. You should not initialize slider inside hidden blocks
2. You should initialize it only after showing. I'm sure you script, which is switching block visibility have some callbacks (onOpen, onShow, onChange etc.). Inside this callback you can start slider.

**Comment by marcobaldo** [comment]
Hi @IonDen - your suggestion worked. This is what I did and works great. - no more jumpy handles.
```
var slider_dom = $('#slider');
$('#parent').hover(function() {
    var slider = slider_dom.data('ionRangeSlider');
    if (slider == null) {
        slider_dom.ionRangeSlider();
    }
}
