### ISSUE TITLE
Slider stuck at Max if from, to and intervals are declared

### ISSUE THREAD

**Issue by Singleshutter** [IonDen/ion.rangeSlider#501]
If the Ion Range Slider has custom Interval values, and then initialize the 'from' and 'to' values, the slider gets bugged and slider point will be stuck at Maximum.

I was able to replicate the bug on jsfiddle, check it out here: [http://jsfiddle.net/mad2vdyw/4/](url)

**Comment by IonDen** [comment]
Hey, just checked your demo. No bug was found. I was able to drag the handle.

**Comment by aharith** [comment]
i have this exact same problem. I use type: double, custom interval value and both slider started at max. It's not stuck, its draggable but its wrong. i specified the from and to value but both slider still start at max value.

**Comment by IonDen** [comment]
@aharith, hi, could you show me your setup? Use this demo: http://jsfiddle.net/IonDen/726L0aj5/

**Comment by aharith** [comment]
Hi, sorry for the late reply. here you go. http://jsfiddle.net/726L0aj5/20/

**Comment by IonDen** [comment]
@aharith, still cant reproduce. I can move handle.

**Comment by SlavaJan** [comment]
Hey, **@IonDen**! Let me bump this issue up.
Look the problem in the fiddle by **@aharith** is that he explicitly declared **_from=1000_** and **_to=200000_** values but on page load both handles start at the maximum position of **_300000_**. Of course you can move them, but the problem is that I want them to be at the exact positions provided in **from** and **to** right after the page is loaded.
Such behavior only happens with custom values array.

**Comment by SlavaJan** [comment]
Thank you! Using indexes worked for me.
