### ISSUE TITLE
How to show numbers on slider in specific format?

### ISSUE THREAD

**Issue by LaxdeepBomble** [IonDen/ion.rangeSlider#533]
Hi,
Thanks for making such amazing slider.

I am stuck at following scenario. 
I want to show the double digit integer values on slider in format like: 01, 02, .... 10, 99. etc.
For this reason, I have added the values in array in string format like ["01","02" ..... etc] and pass it to the slider.
But still somehow, slider shows values in default format : 1,2,....,10, 99.

How to show values in such format on slider?

**Comment by IonDen** [comment]
Hi, take a look on this demo: http://jsfiddle.net/IonDen/vrqqL2Lw/
Idea is similar, you need to write your own prettify function to transform numbers.

**Comment by slidenerd** [comment]
thanks for the link @IonDen i was looking at your earlier posts and was trying to find how i can change the prettify format for from and to , if i have a slider that shows rank from 1 to 1000, i would like the prettify function to show 'Rank 1' for the starting value but only '1000' for the ending value instead of 'Rank 1000' that it does by default. Any suggestions/pointers are super appreciated, couldnt find an issue on this one

**Comment by IonDen** [comment]
@slidenerd, ok, i understand what you want.

Here is a workaround:
http://jsfiddle.net/x5fqupnp/ - you can hide one of prefixes/postfixes with CSS
