### ISSUE TITLE
rangeSlider with values and smooth pulling

### ISSUE THREAD

**Issue by liderbudowlany** [IonDen/ion.rangeSlider#543]
Hi, I downloaded your script and it is very, very GREAT, but I am looking for on modification. 
Please look at your demo: 
http://ionden.com/a/plugins/ion.rangeSlider/demo.html
and see demo Basic with Modern Skin, example #range_07
There is a static values which user can pick, but when he pull the marker then he doesn't move until he reach some value. What I want is the marker will move smooth, but when user put down marker then he goes to the nearest value.
See my example of rangeslider:
https://imgur.com/26GYaO5
I am holding on the marker and marker doesn't go with mouse, he jumps between values.
What I want to reach is this:
https://imgur.com/YqJeJWr
But when user put down marker then market goes to nearest value.

**Comment by IonDen** [comment]
Hello, you can not do that from the box.

This is working like this because we have this chain of events:
1. Then you drag a handle
2. We are getting mouse position
3. We are converting it to %
4. We execute a Math.round function to convert % to real number
5. We convert real number to % back
6. We draw the new position of handle

So, to override this, you can experiment with `calcWithStep` function.

**Comment by liderbudowlany** [comment]
So I need to edit something in the core, or calcWithStep is the one of the options?

**Comment by IonDen** [comment]
`calcWithStep` - is the best idea where to start from.
