### ISSUE TITLE
initialize slider on Symfony

### ISSUE THREAD

**Issue by veystar** [IonDen/ion.rangeSlider#596]
Hello,
I'm trying to insert Ion Slider into my Symfony 4 project. If I coding the slider in separate HTML file, it works fine. When I'm inserting it to html.twig, it disappears and shows me just empty input field. I can't understand why? Please help...

**Comment by IonDen** [comment]
Hi. If you will open browser console you will probably see some errors.

Empty input filed means that plugin was not launched at all, because of some problem.
Usually main reason is that jQuery is not included in project or started later then plugin.

Google "using jquery plugin in my symfony project"
